src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix = null;

    #[ORM\ManyToOne(inversedBy: 'locations')]
    private ?Client $client = null;

    #[ORM\ManyToOne(inversedBy: 'locations')]
    private ?Voiture $voiture = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): static
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }
    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;

        return $this;
    }
}

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Serie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Modele = null;

    #[ORM\Column(nullable: true)]
    private ?float $Prix_jour = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Date_Mise_En_Marche = null;


    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Location::class)]
    private Collection $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?string
    {
        return $this->Serie;
    }

    public function setSerie(string $Serie): static
    {
        $this->Serie = $Serie;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->Modele;
    }

    public function setModele(?string $Modele): static
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getPrixJour(): ?float
    {
        return $this->Prix_jour;
    }

    public function setPrixJour(?float $Prix_jour): static
    {
        $this->Prix_jour = $Prix_jour;

        return $this;
    }

    public function getDateMiseEnMarche(): ?\DateTimeInterface
    {
        return $this->Date_Mise_En_Marche;
    }

    public function setDateMiseEnMarche(?\DateTimeInterface $Date_Mise_En_Marche): static
    {
        $this->Date_Mise_En_Marche = $Date_Mise_En_Marche;

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setVoiture($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getVoiture() === $this) {
                $location->setVoiture(null);
            }
        }

        return $this;
    }
}

src/Form/LocationType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Location;
use App\Entity\Voiture;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('date_retour')
            ->add('client', EntityType::class,
            [
                "class"=>Client::class,
                "choice_label"=>function($client) {
                    return $client->getNom() . ' ' . $client->getPrenom();}

            ])
            ->add('voiture',EntityType::class,
                [
                    "class"=>Voiture::class,
                    "choice_label"=>"Serie"
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Location::class,
        ]);
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Form\LocationType;
use App\Repository\LocationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/location')]
class LocationController extends AbstractController
{
    #[Route('/', name: 'app_location_index', methods: ['GET'])]
    public function index(LocationRepository $locationRepository): Response
    {
        return $this->render('location/index.html.twig', [
            'locations' => $locationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_location_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $location = new Location();
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $prix = 0;
            //Nbre de jours
            $nbrj = $location->getDateRetour()->diff($location->getDateDebut())->days;

            //prixJour Voiture
            $prixJour = $location->getVoiture()->getPrixJour();

            //Calcul prix
            $prix = $prixJour * $nbrj;

            $location->setPrix($prix);
            $entityManager->persist($location);
            $entityManager->flush();

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('location/new.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_show', methods: ['GET'])]
    public function show(Location $location): Response
    {
        return $this->render('location/show.html.twig', [
            'location' => $location,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_location_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Location $location, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('location/edit.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_delete', methods: ['POST'])]
    public function delete(Request $request, Location $location, EntityManagerInterface $entityManager): Response
    {
            $entityManager->remove($location);
            $entityManager->flush();
        
        return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/location/_delete_form.html.twig
<form method="post" action="{{ path('app_location_delete', {'id': location.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ location.id) }}">
    <button class="btn">Delete</button>
</form>

templates/location/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/location/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Location{% endblock %}

{% block body %}
    <h1>Edit Location</h1>

    {{ include('location/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_location_index') }}">back to list</a>

    {{ include('location/_delete_form.html.twig') }}
{% endblock %}

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Location index{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        /* Add your CSS styles here */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        a {
            text-decoration: none;
            color: #007bff;
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Location index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date Debut</th>
                <th>Date Retour</th>
                <th>Prix</th>
                <th>Client</th>
                <th>Voiture</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for location in locations %}
            <tr>
                <td>{{ location.id }}</td>
                <td>{{ location.getDateDebut() ? location.getDateDebut() | date('Y-m-d') : '' }}</td>
                <td>{{ location.getDateRetour() ? location.getDateRetour() | date('Y-m-d') : '' }}</td>
                <td>{{ location.prix }}</td>
                <td>{{ location.client.nom }}</td>
                <td>{{ location.voiture.serie }}</td>
                <td>
                    <a href="{{ path('app_location_show', {'id': location.id}) }}">show</a>
                    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_location_new') }}">Create new</a>
{% endblock %}

templates/location/new.html.twig
{% block title %}New Location{% endblock %}

{% block stylesheets %}
    
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            /* Add more styles as needed */
        }

        h1 {
            color: #333;
        }

        /* Add more styles as needed */
    </style>
{% endblock %}

{% block body %}
    <h1>Create new Location</h1>

    {{ include('location/_form.html.twig') }}

    <a href="{{ path('app_location_index') }}">back to list</a>
{% endblock %}

templates/location/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Location{% endblock %}

{% block body %}
    <h1>Location</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ location.id }}</td>
            </tr>
            <tr>
                <th>DateD</th>
                <td>{{ location.getDateDebut() ? location.getDateDebut() |date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>DateA</th>
                <td>{{ location.getDateRetour() ? location.getDateRetour() |date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ location.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_location_index') }}">back to list</a>

    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>

    {{ include('location/_delete_form.html.twig') }}
{% endblock %}