src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Serie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Modele = null;

    #[ORM\Column(nullable: true)]
    private ?float $Prix_jour = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Date_Mise_En_Marche = null;


    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Location::class)]
    private Collection $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?string
    {
        return $this->Serie;
    }

    public function setSerie(string $Serie): static
    {
        $this->Serie = $Serie;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->Modele;
    }

    public function setModele(?string $Modele): static
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getPrixJour(): ?float
    {
        return $this->Prix_jour;
    }

    public function setPrixJour(?float $Prix_jour): static
    {
        $this->Prix_jour = $Prix_jour;

        return $this;
    }

    public function getDateMiseEnMarche(): ?\DateTimeInterface
    {
        return $this->Date_Mise_En_Marche;
    }

    public function setDateMiseEnMarche(?\DateTimeInterface $Date_Mise_En_Marche): static
    {
        $this->Date_Mise_En_Marche = $Date_Mise_En_Marche;

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setVoiture($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getVoiture() === $this) {
                $location->setVoiture(null);
            }
        }

        return $this;
    }
}

src/Form/VoitureForm.php
<?php

namespace App\Form;

use App\Entity\Modele;
use phpDocumentor\Reflection\Types\Float_;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class VoitureForm extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('Serie', TextType::class)
        ->add('Date_Mise_En_Marche', DateType::class)
        ->add('Prix_jour', NumberType::class)
        ->add('Modele', TextType::class);
}
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;


use App\Entity\Voiture;
use App\Form\VoitureForm;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class VoitureController extends AbstractController
{
    #[Route('/voiture', name: 'app_voiture')]
    public function listeVoiture(VoitureRepository $vr): Response
    {
        $voitures = $vr->findAll();
        return $this->render('voiture/listeVoiture.html.twig', [
            'listeVoiture' => $voitures,
        ]);
    }

    #[Route('/addVoiture', name: 'addVoiture')]
    public function addVoiture(Request $request,
                               EntityManagerInterface $em)
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureForm::class,$voiture );
        $form->handleRequest($request);
        if($form->isSubmitted()){
            $em->persist($voiture);//prépare la requête sql (insert into ...)
            $em->flush(); //commit dans la bd
            return $this->redirectToRoute("app_voiture");
        }
        return $this->render("voiture/addVoiture.html.twig",
        ["formV"=>$form->createView()]);
    }


    #[Route('/voiture/{id}', name: 'voitureDelete')]
    public function delete(EntityManagerInterface $em, VoitureRepository$vr, $id): Response
    {
        $voiture = $vr->find($id);
         $em->remove($voiture);
         $em->flush();

        return $this->redirectToRoute('app_voiture');
    }

    #[Route('/updateVoiture/{id}', name: 'voitureUpdate')]
    public function updateVoiture(Request $request, EntityManagerInterface $em,
                                  VoitureRepository$vr, $id): Response
    {

        $voiture = $vr->find($id);

        $editform = $this->createForm(VoitureForm::class, $voiture);

        $editform->handleRequest($request);

        if ($editform->isSubmitted() and $editform->isValid()) {

            $em->persist($voiture);
            $em->flush();

            return $this->redirectToRoute('app_voiture');
        }
        return $this->render('voiture/updateVoiture.html.twig', [
            'editFormVoiture'=>$editform->createView()
        ]);
    }


    #[Route('/searchVoiture', name: 'voitureSearch')]
    public function searchVoiture(Request $request, EntityManagerInterface $em): Response
    {
        $voitures = null;

        if($request->isMethod('POST')){
            $serie = $request->request->get("input_serie");
            $query = $em->createQuery(
                "SELECT v FROM App\Entity\Voiture v 
                   where v.serie LIKE '".$serie."'");

            $voitures = $query->getResult();
        }

        return $this->render("voiture/rechercheVoiture.html.twig",
            ["voitures"=>$voitures]);
    }
}

templates/voiture/addVoiture.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAJ d'une Voiture</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input[type="text"],
        input[type="date"],
        input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #3498db;
            color: #fff;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #207bd4;
        }
    </style>
</head>
<body>
<form method="post">
    {{ form_widget(formV) }}
    <input type="submit" value="addVoiture">
</form>
</body>




templates/voiture/listeVoiture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des voitures{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        h1 {
            color: #333;
            font-family: Arial, sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        a {
            text-decoration: none;
            color: #007bff; /* Blue color for links */
        }

        /* Add more styles as needed */
    </style>
{% endblock %}

{% block body %}
    <h1>Liste des voitures</h1>
    <table>
        <tr>
            <td>ID</td>
            <td>Serie</td>
            <td>Modele</td>
            <td>Date</td>
            <td>Prix Jour</td>
            <td>Action</td>
            <td>Action</td>
        </tr>
        {% for v in listeVoiture %}
            <tr>
                <td>{{ v.id }}</td>
                <td>{{ v.Serie }}</td>
                <td>{{ v.Modele }}</td>
                <td>{{ v.getDateMiseEnMarche() | date}}</td>
                <td>{{ v.getPrixJour() }}</td>
                <td><a href="{{ path("voitureDelete", {'id': v.id}) }}">Supprimer</a></td>
                <td><a href="{{ path("voitureUpdate", {'id': v.id}) }}">MAJ</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/voiture/rechercheVoiture.html.twig
<h1>Recherche Voiture</h1>
<form action="" method="POST">
    serie : <input type="text" name="input_serie">
    <input type="submit" value="Rechercher">
</form>

{%  if voitures is empty %}
Aucune voiture trouvée

{% else %}
    <table border="1">
        <tr>
            <td>Serie</td>
            <td>Modele</td>
        </tr>
        {% for v in voitures %}
            <tr>
                <td>{{ v.serie }}</td>
                <td>{{ v.modele}}</td>
            </tr>
        {% endfor %}
    </table>

{% endif %}




templates/voiture/rechercheVoitureModele.html.twig
<h1>Recherche Voiture</h1>
<form action="" method="POST">
    Libelle : <input type="text" name="input_libelle">
    <input type="submit" value="Rechercher">
</form>

{%  if voitures is empty %}
Aucune voiture trouvée

{% else %}
    <table border="1">
        <tr>
            <td>Serie</td>
            <td>Modele</td>
        </tr>
        {% for v in voitures %}
            <tr>
                <td>{{ v.serie }}</td>
                <td>{{ v.modele.libelle }}</td>
            </tr>
        {% endfor %}
    </table>

{% endif %}




templates/voiture/updateVoiture.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAJ d'une Voiture</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input[type="text"],
        input[type="date"],
        input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #3498db;
            color: #fff;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #207bd4;
        }
    </style>
</head>
<body>

    <h1>MAJ d'une Voiture</h1>

    <form action="" method="Post">
        {{ form_widget(editFormVoiture) }}
        <input type="submit" value="MAJ Voiture">
    </form>

</body>
</html>